### ISSUE TITLE
Combine versions upgrade and rolling upgrade docs

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#1010]
### Describe the Issue

Address comment in #960 (https://github.com/redpanda-data/documentation/pull/960#pullrequestreview-1242231266):

- Because the [versions upgrade](https://docs.redpanda.com/docs/platform/install-upgrade/version-upgrade/) and [rolling upgrade](https://docs.redpanda.com/docs/platform/install-upgrade/rolling-upgrade/) docs are interrelated, investigate combining them into a single page to improve their readability and usability.

### Updates to existing documentation

Combine [versions upgrade](https://docs.redpanda.com/docs/platform/install-upgrade/version-upgrade/) and [rolling upgrade](https://docs.redpanda.com/docs/platform/install-upgrade/rolling-upgrade/) docs.

**Comment by Feediver1** [comment]
@micheleRP So when we went through the navtree updates, @rkruze suggested we remove the Version Upgrade topic (view [here](https://docs.redpanda.com/docs/22.2/install-upgrade/version-upgrade/) in a previous version). Now that we have removed it, we've discovered a bit of a problem in the context of [Rolling Upgrades](https://docs.redpanda.com/docs/manage/cluster-maintenance/rolling-upgrade/#performing-a-rolling-upgrade). Currently, Rolling Upgrades only describes how to put the cluster in maintenance mode, and lacks any content about actually upgrading. Not good. My suggestion is to grab the Version upgrade content from an older repo and work it into the Rolling Upgrade docs so that there is actually an upgrade task within it (as the tile suggest). Without it, the Rolling Upgrade topic is really a Set Maintenance Mode topic. 

Also, please remove the numbers from the headings - not a good practice to put the step numbers in headings. Also think about whether or not numbered steps are required in the first task...and if there is only one step in a heading, then it should not be numbered. Thx.

@rkruze If this guidance is not aligned with the way our users perform rolling upgrades, please share any suggestions/feedback. Thanks!

**Comment by Feediver1** [comment]
During cluster upgrade, the logical cluster version is incremented only when the last active broker is upgraded, marking the 'point of no return' with upgrades, as downgrades are not supported. If problems occur with specific brokers that are active, the upgrade is not committed.

Additionally, beginning with 22.1, new feature enablement is intentionally suppressed until all brokers are upgraded to prevent unexpected behavior relating to new features.

Both of these facts are important for operators but are missing from : https://docs.redpanda.com/docs/cluster-administration/version-upgrade/

**Comment by Feediver1** [comment]
^^ From closed duplicate ticket

**Comment by Feediver1** [comment]
Please also include the request from https://github.com/redpanda-data/documentation/issues/415

**Comment by hcoyote** [comment]
The Version Upgrade topic appears to have had an important piece of context regarding going from one major version to another. I can't find anything similar talking about it in 22.3 docs.

> Redpanda only supports upgrading one version at a time. For example, upgrading from `22.1` to `22.2` is supported, while upgrading from `22.1` directly to `22.3` is not. In the latter case, you would upgrade first to `22.2`, and then to `22.3`.


And more specifically, the guidance appears to be 

> the supported upgrade path should be through each minor release latest patch. so from v22.1.3 -> v22.1.latest -> v22.2.latest -> v22.3.latest
