### ISSUE TITLE
Linux production deployment guide has broken links in the ToC

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#1118]
### Describe the Issue

We are using headings inside tabs in the Linux deployment guide, which is causing them to appear in the table of contents.

We shouldn't need to use headings in those tabs, and I'm not sure if the content in those tabs even belongs in the Suggested reading section.

![2023-01-27_16-45-02](https://user-images.githubusercontent.com/45230295/215144318-984d904f-ca10-489f-988a-ca25b45c78e4.png)

### Updates to existing documentation

https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment

**Comment by Feediver1** [comment]
This looks like a mistake during navtree updates. Suggested reading should always be the last heading in any topic.

**Comment by Feediver1** [comment]
Revising this to P1 as all of these links are dead--anyone clicking them will not get the content they are seeking.Not a product failure, but a doc failure.

**Comment by shorgi** [comment]
Reviewed this in the context of #1210 . The root cause is that all headings in all tabs are shown in the (right-nav) TOC:
- The headings of the first (enabled) tab are listed first. These are all reachable from the TOC links.
- The headings of the second (disabled) are listed next. The are all _not_ reachable from the TOC links.

The workarounds are 
1. Split the tabs into separate pages.
2. Split the tabs into separate sections/headings.
