### ISSUE TITLE
Document Controller Snapshots (23.2)

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/documentation#1552]
https://github.com/redpanda-data/core-internal/issues/132

Controller snapshots are somewhat of an implementation detail, but they'll show up for cluster admins and in support incidents as much faster cluster restart / start times, drastically reduce time to add a new node, etc. . This is good for admins to understand (as compared to the previous 'always load the entire controller log on startup' behavior of 23.1 and before)

Snapshots will eventually be used in our metadata backup/DR efforts , but this doc ticket is purely about highlighting how snapshotting works and how redpanda's controller log is managed in general (we can now load the snapshot and replay only incremental updates since the last snapshot to have new and restarted nodes become operational sooner

**Comment by Feediver1** [comment]
SME = @ztlpn

**Comment by micheleRP** [comment]
Hi @ztlpn and @mattschumpert: Our doc currently only explains the cluster controller in [Decommission Brokers](https://docs.redpanda.com/docs/manage/cluster-maintenance/decommission-brokers/). Is this the right place to document this snapshot? Or we could add it in [Cluster Diagnostics](https://docs.redpanda.com/docs/manage/cluster-maintenance/cluster-diagnostics/)?

**Comment by mattschumpert** [comment]
Wonder if its worth mentioning this wherever we talk about broker startup/restart in general (it could take minutes before this)

**Comment by micheleRP** [comment]
Hi @ztlpn and @mattschumpert. We don’t currently document anything about the controller log or its behavior at startup. For 23.2, is it sufficient to just add the following note:

_Redpanda takes periodic snapshots of the controller log. This allows Redpanda to load the snapshot on startup with just recent events (instead of the entire controller log), enabling fast startup and restart times._ 

We could add it [here in deployment](- https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/production/dev-deployment/#start-redpanda) and/or [here in how Redpanda works](- https://docs.redpanda.com/docs/get-started/architecture/)? 

Are either of these other doc sections impacted by this new functionality? 
- https://docs.redpanda.com/docs/manage/cluster-maintenance/rolling-upgrade/#impact-of-broker-restarts 
- https://docs.redpanda.com/docs/manage/cluster-maintenance/configure-availability/#prevent-crash-loops

**Comment by ztlpn** [comment]
FYI here are the internal docs for controller snapshots that I wrote: https://vectorizedio.atlassian.net/wiki/spaces/CORE/pages/382468112/Controller+snapshots

**Comment by micheleRP** [comment]
> FYI here are the internal docs for controller snapshots that I wrote: https://vectorizedio.atlassian.net/wiki/spaces/CORE/pages/382468112/Controller+snapshots

Thanks @ztlpn, all very helpful! Please review #1646
