### ISSUE TITLE
Document Error Code in Redpanda

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/documentation#248]
### Who is this for and what problem do they have today?

While playing around Redpanda, users usually receive an error with a corresponding error code like:

```
archival metadata STM update failed: cluster::errc:13
```

But it's unclear what `13` actually means. Uses may google it but we, Redpanda, doesn't provide anything about it.

### What would you like fixed in or added to the documentation?

As Apache Kafka has https://kafka.apache.org/11/protocol.html#protocol_error_codes, let's document Redpanda's error code too.

The error code is basically defined in `errc.h` or in `errors.h` in each component like below:

https://github.com/redpanda-data/redpanda/blob/dev/src/v/rpc/errc.h
https://github.com/redpanda-data/redpanda/blob/dev/src/v/cluster/errc.h
https://github.com/redpanda-data/redpanda/blob/dev/src/v/kafka/protocol/errors.h

We should have the corresponding tables per component.

### Is this a new feature or a gap in the documentation?

New feature

### Link to existing product documentation page and/or community slack conversation, if applicable

This was originally raised while troubleshooting a customer issue, https://redpandadata.slack.com/archives/C032D7VUFEE/p1645218956913879

**Comment by Feediver1** [comment]
Asked in #help-core: https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1675112169363269
Awaiting guidance.

**Comment by Feediver1** [comment]
@daisukebe This appears to be partially addressed by the fix from @jcsp last month. If you follow the Slack request I made re docs creating  an error code reference, there was little to no support from engineering. I am closing as not planned. If you still feel that we need this type of documentation--that it will improve the customer experience, it will have to also be prioritized by PM/eng too, so that docs has the necessary eng resources to make this happen. Hopefully, John's update at least takes care of the confusion about the meaning of `13` in the example you submitted. Thx.
