### ISSUE TITLE
Partition assignment API

### ISSUE THREAD

**Issue by h-garcia** [redpanda-data/documentation#46]
Our field folks are looking for more content around day 2, 3 operations to help with landing deals. So it would be great to have content on the following

**AC**

- Document (article/page) Partition assignment API

**Comment by Feediver1** [comment]
There are two ticket open that should address this request:
https://github.com/redpanda-data/documentation/issues/792
will divvy up topics in the context of personas, getting started (day 1), Develop, & Deploy (day 2).
As for the SPI doc request, this issue is part of the planned 22.4 feature set:
https://github.com/redpanda-data/documentation/issues/606
