### ISSUE TITLE
60-seconds-to-wow should have console in the docker compose

### ISSUE THREAD

**Issue by emaxerrno** [redpanda-data/documentation#666]
This post should have the whole platform. 

How to get up and running in 60 seconds with a UI should have console.

https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file

similarly here

https://docs.redpanda.com/docs/console/installation/#docker

**Comment by Feediver1** [comment]
See email from customer (Ezequiel Panepucci (epanepucci@gmail.com) on Sept 27, 2022 at 4:11 AM @AnneLeeperRP for when you respond/close the loop after fixing. Thx.

**Comment by AnneLeeperRP** [comment]
@weeco Can you please let me know what needs to be added to our existing docker instructions?

It looks like we need to add a line to the `docker-compose.yaml` file in the "60-Second Guide" for Docker.
I'm not sure what needs to be added to the Docker section of the Installation instructions under "Console", since that section only has two sentences and no commands.
Thank you!

**Comment by AnneLeeperRP** [comment]
Pinged @weeco in Slack as a reminder. I think this is a one-liner in the `.yaml` file, but I need the syntax.

**Comment by weeco** [comment]
@AnneLeeperRP @Feediver1 ,
the Console docs section has a a "Docker compose configuration" - you only need to merge in the relevant parts into the existing docker compose files. Here's the docker compose in the Console section that runs Redpanda and Console (and Kafka connect + owl shop for demo data): https://docs.redpanda.com/docs/console/reference/docker-compose/

Does that help you?

PS: Please don't expect that I react to GitHub notifications, I receive ~50-100 emails from GitHub every week

**Comment by JakeSCahill** [comment]
Closing in favor of https://github.com/redpanda-data/documentation/issues/593
