### ISSUE TITLE
bad links to community slack

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#788]
### Describe the Issue

Links to community slack are not working; e.g., see every page on the website with links to Community:

[Redpanda](https://redpanda.com/) Logo
Redpanda
[Resources](https://redpanda.com/resources/)
[Training](https://university.redpanda.com/)
[Blog](https://redpanda.com/blog/)
[Helpdesk](https://support.redpanda.com/hc/en-us/)
[Community](https://rpnda.co/slack)
[GitHub](https://github.com/redpanda-data/redpanda/)

Also:
https://docs.redpanda.com/docs/platform/data-management/data-migration/
https://docs.redpanda.com/docs/platform/labs/
https://docs.redpanda.com/docs/platform/labs/install-preview/

**Comment by Feediver1** [comment]
we should change the bitly link to [redpanda.com/slack](http://redpanda.com/slack)

**Comment by Deflaimun** [comment]
The problem was that Slack's invite was invalid and it looks like the link was fixed internally by @dhruv-gupta team. We also tested all the links that we use and they're correctly redirecting to the same invite URL. So this PR is not necessary anymore.

If we still to do this please reopen the issue.

PR: https://github.com/redpanda-data/documentation/pull/803
