### ISSUE TITLE
Create the site structure for dedicated Kubernetes docs

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/documentation#856]
## Assumptions

We want to allow users to find all docs related to Kubernetes deployments easily.

## Options

I see two options for doing so:

1. Use tags.
1. Use a dedicated sidebar.

### Using tags

We can [tag content in the frontmatter](https://docusaurus.io/docs/create-doc#doc-tags), allowing users to filter content by tags.

1. Define tags such as Kubernetes, Redpanda Operator, and Redpanda Helm Chart.
1. Add tags to the frontmatter of any relevant pages.

#### Pros

- Simple. Keep all content where it is (in the Redpanda Platform docs).
- No significant architectural changes.
- Kubernetes docs can be versioned according to the latest supported version of Redpanda Platform.

#### Cons

By default, the landing page for tags is just a list of doc titles and descriptions in alphabetical order. Will users be willing to navigate this way? Will we need to customize this behavior somehow?

### Using a dedicated sidebar

We can provide users with a dedicated sidebar as we do with Redpanda Cloud.

We have two ways of achieving this:

1. Move all Kubernetes content to a dedicated `kubernetes` directory.
1. Update `static/_redirects` to handle existing links to the old paths.
1. Update relative links to the new paths.

Or:

1. Leave all Kubernetes content where it is and just configure a new sidebar.

#### Pros

- A dedicated sidebar for Kubernetes documentation.
- **Only for the first way**: Docs available at a dedicated URL path `/docs/kubernetes/`.

#### Cons

- We add an additional layer of complexity when it comes to content that applies to multiple products. Do we expect users to navigate between content where the sidebar structure changes? Do we use React components to define reusable snippets? For example, K8 users will also need to read the rpk reference.

- **Only for the first way**: Lots of changes and handling broken links.

#### Open questions

1. How should we deal with versioning the Kubernetes documentation?
- Version according to the Helm chart? Which one? The currently recommended chart? The chart for Redpanda Operator?
- Version according to the latest supported version of Redpanda?
- Don't version the Kubernetes docs. Will users stumble across new features that aren't available in their version of the Helm chart?

2. For the home page of Kubernetes docs, what should we display?
- Docs by tools?
- Docs by persona?
- What images shall we use?
- Is there a style guide or a template for creating new images?

**Comment by Feediver1** [comment]
Initial thoughts here @JakeSCahill:

- I'm partial to the dedicated sidebar ( including the 3 listed options) because it helps users make sense of the content/give the content context. The tagged list does neither. The customer experience with the content and its structure/organization is paramount--our north star. A contextless list of topics sounds like a very unpleasant/unhelpful user experience.
- Please vet with PM (@vladoschreiner ), but the versioning should be the same for the rest of the platform doc content. An exception would be if we did not support certain versions of k8s, but that's a separate topic altogether. You may want to run this by @joejulian too.
- For the home page of Kubernetes docs, I suggest a left sidenav as you see in [our platform](https://docs.redpanda.com/docs/home/platform/) and [Confluent for Kubernetes](https://docs.confluent.io/operator/current/overview.html) docs. However, the home/landing page should have workflow "buckets" to assist customers in their journey as they implement Redpanda. I am working with @rkruze on a revision of the current platform landing page (you can view a rough draft/outline of the workflow "buckets" [here](https://docs.google.com/document/d/1ky1Sumz_cywclV9L8dYIkCNrqm-ae2o8UW65QNfwNQU/edit?usp=sharing)). I defer to Roko on this though, as he and his team work with our RP k8s customers on a daily basis and fully understand their challenges/implementation requirements.

**Comment by JakeSCahill** [comment]
Thanks @Feediver1 ! Is the URL path important here? One of the ways of creating a dedicated sidebar also includes a dedicated URL path of `/docs/kubernetes/`. AFAIK, this may help with SEO and make our K8 content more findable. PingCap also do this. For example: https://docs.pingcap.com/tidb-in-kubernetes/stable/monitor-a-tidb-cluster

**Comment by JakeSCahill** [comment]
Status: Checking on the impact of URL paths on SEO with Justin.

**Comment by JakeSCahill** [comment]
As an example:

- Leave the content where it is in the file tree, so we will have paths like https://docs.redpanda.com/docs/platform/quickstart/kubernetes-qs-dev/
- Move the content into a new structure, so we will have paths like https://docs.redpanda.com/docs/kubernetes/helm/quick-start/

From Justin:

URL paths are important, but only insofar that they are:
Relatively short (the absolute max is 2,000 characters, but shorter is always better)
Human-readable
As part of (2), the URL should include the focus keyword in the path (so, in this case, it's important that the URL include kubernetes and quickstart somewhere in it. The space vs. no space in quick start is irrelevant. Search engines will treat them as synonyms.)
For how the file tree is arranged, that doesn't matter. I'd opt for what would be the most intuitive for users, and if there isn't a clear favorite, I might choose the second one because it's shorter.

**Comment by JakeSCahill** [comment]
Status: We are going to leave content where it is in the current structure, following a similar approach to CockroachDB: https://www.cockroachlabs.com/docs/v22.1/kubernetes-overview.html
