### ISSUE TITLE
add documentation on console telemetry

### ISSUE THREAD

**Issue by emaxerrno** [redpanda-data/documentation#961]
redpanda console collects simple telemetry to help us optimize the product usage like batch size, topic compacted or regular, etc. 

@weeco wrote the property to disable it on the release notes of the latest redpanda console release but we haven't pushed this config to the docs site, so we have to just sync it. 

cc: @Feediver1

**Comment by weeco** [comment]
The config is documented in Console's reference config on our docs. Is the ask to create a dedicated page for telemetry?

**Comment by Feediver1** [comment]
@emaxerrno Awaiting your guidance before we update docs. Looks like the config you are requesting is already in the doc: 
https://docs.redpanda.com/docs/platform/console/reference/config/#sample-configuration

Is there something other than the config updates from @weeco that you want docs to address?

**Comment by shorgi** [comment]
@emaxerrno - given that the property to disable simple telemetry collection is [documented in the docs' sample configuration file](https://docs.redpanda.com/docs/reference/console/config/#:~:text=evaluate%20feature%20usage.-,analytics%3A,-enabled%3A%20true), please comment and clarify about any additional docs by Tue Jan 24. Otherwise, we'll close this issue and reopen later as needed.

**Comment by Feediver1** [comment]
Content appears to be in the docs now. Please re-open if we missed anything @emaxerrno . Thanks.
