### ISSUE TITLE
Revise autotuner docs

### ISSUE THREAD

**Issue by shorgi** [redpanda-data/documentation#979]
The Redpanda autotuner docs, https://docs.redpanda.com/docs/platform/introduction/autotune/, are out of date.

Todo:
- Update and single-source content
- Create issue to update tools to point to new doc

**Comment by micheleRP** [comment]
See this comment about auto-tuning: https://github.com/redpanda-data/documentation/pull/890#discussion_r1038367035

@jrkinley: What is the auto-tuning tool? Is it rpk iotune or rpk redpanda tune?

@travisdowns travisdowns yesterday
I think it's both, but there is some complication around containers: running redpanda in a container is more complicated because (a) I am not sure the rpk well-known-io detection logic will work inside a container or it may depend on the container networking config (see https://redpandadata.slack.com/archives/C024H6DSU2H/p1673450827074599) and (b) it is less clear how to run rpk iotune: you can't just run it on the host or inside the container, probably it has to be run on the host then the results written to somewhere accessible to the container, which we don't really document.

In general we don't document much about rpk iotune except that it exists and you should run it: probably an area for improvement?

**Comment by shorgi** [comment]
Include content on `rpk mode production`, as raised in https://redpandadata.slack.com/archives/C03KAHQ776C/p1674159983464419.

**Comment by Feediver1** [comment]
@shorgi Please be sure to tag @dhruv-gupta and @weimeilin79 in the PR so they are aware when the PR gets merged. They will need the final URL for links they have in the RPU docs. Thx!
